#!/usr/bin/env ruby
load "#{ENV['HOME']}/.git_hooks/current_branch.rb"

protected_branch = ENV['PROTECTED_BRANCH'] || 'master'
current_branch = CurrentBranch.new.name
exit_time = (ENV['EXIT_TIME'] || 10).to_i

trap "SIGINT" do
  print "\n\e[42;1mCanceling pushing to #{protected_branch} \e[0m\n"
  exit 0
end

if current_branch == protected_branch
  puts "\e[41;1mYou are about to push to #{protected_branch}. Press CTRL + C in #{exit_time} sec\e[0m"

  while exit_time > 0
    print "\e[42;1m=============\e[0m\e[41m#{exit_time}\e[42;1m==================\e[0m\r"
    sleep 1
    exit_time -= 1
    $stdout.flush
  end
  exit 0
end
